# Generated by Django 5.1.2 on 2024-11-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_category_alter_ejournal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('book', 'Book'), ('e_journal', 'E-Journal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ejournal',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('book', 'Book'), ('e_journal', 'E-Journal')], max_length=20, null=True),
        ),
    ]
