# Generated by Django 5.1.2 on 2024-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_viewedresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedresource',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
